// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJOdvOj5P4wJsIUUbbDovps-YOVHibHUc',
    appId: '1:572329223623:web:c45b98347edfd7eb0265e2',
    messagingSenderId: '572329223623',
    projectId: 'evolv-a53b7',
    authDomain: 'evolv-a53b7.firebaseapp.com',
    storageBucket: 'evolv-a53b7.firebasestorage.app',
    measurementId: 'G-Y88PXM46ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUM9UWjAecd9Entf6vYSAaCzF_dTPFSUo',
    appId: '1:572329223623:android:35c56d037e4c49ca0265e2',
    messagingSenderId: '572329223623',
    projectId: 'evolv-a53b7',
    storageBucket: 'evolv-a53b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc8m0OOssg16K7pZ67CUkesuMtkE6OPxE',
    appId: '1:572329223623:ios:ff17a0ded877adac0265e2',
    messagingSenderId: '572329223623',
    projectId: 'evolv-a53b7',
    storageBucket: 'evolv-a53b7.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );
}
